### ISSUE TITLE
NoClassDefFoundError: net/imglib2/img/cell/AbstractCellImgFactory

### ISSUE THREAD

**Issue by danielsnider** [imglib/imglib2-tutorials#2]
When running `/imglib2-tutorials/src/main/java/Example1b.java` I get this error. (A solution is given below)

```
Exception in thread "main" java.lang.NoClassDefFoundError: net/imglib2/img/cell/AbstractCellImgFactory
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at io.scif.img.ImgOpener.getHeuristic(ImgOpener.java:543)
  at io.scif.img.ImgOpener.openImgs(ImgOpener.java:254)
  at io.scif.img.ImgOpener.openImgs(ImgOpener.java:146)
  at io.scif.img.ImgOpener.openImgs(ImgOpener.java:113)
  at io.scif.img.ImgOpener.openImg(ImgOpener.java:422)
  at Example1b.<init>(Example1b.java:67)
  at Example1b.main(Example1b.java:95)
Caused by: java.lang.ClassNotFoundException: net.imglib2.img.cell.AbstractCellImgFactory
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 19 more
```

If I comment out the pegged version in `pom.xml` and run `mvn clean install` everything works fine.
```
  <dependency>
      <groupId>net.imglib2</groupId>
      <artifactId>imglib2</artifactId>
      <!-- <version>4.3.0</version> I COMMENT THIS TO FIX -->
    </dependency>
```
Thanks to help from @tinevez!

**Comment by tpietzsch** [comment]
👍
